"use client";

import { useEffect, useState } from "react";
import { getNotifications, markAsRead, type Notification } from "@/services/notifications";
import { useBranch } from "@/components/branch-provider";
import { DashboardLayout } from "@/components/layout/dashboard-layout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";
import Link from "next/link";

export default function NotificationsPage() {
  const { effectiveBranchId } = useBranch();
  const [items, setItems] = useState<Notification[]>([]);
  const [loading, setLoading] = useState(true);

  async function load() {
    setLoading(true);
    try {
      const data = await getNotifications({
        limit: 100,
        branchId: effectiveBranchId ?? undefined,
      });
      setItems(data);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    load();
  }, [effectiveBranchId]);

  async function handleMarkAsRead(id: string) {
    await markAsRead(id);
    setItems((prev) =>
      prev.map((n) => (n.id === id ? { ...n, read_at: new Date().toISOString() } : n))
    );
  }

  return (
    <DashboardLayout title="Notifications">
      <Card>
        <CardHeader>
          <CardTitle>Notification center</CardTitle>
          <CardDescription>Alerts, low stock, supplier delays, and ticket updates</CardDescription>
        </CardHeader>
        <CardContent>
          {loading ? (
            <p className="text-muted-foreground">Loading...</p>
          ) : items.length === 0 ? (
            <div className="flex flex-col items-center justify-center rounded-md border border-dashed py-12 text-center text-muted-foreground">
              <p>No notifications yet.</p>
              <p className="text-sm">Notifications will appear here when generated by the system or n8n.</p>
            </div>
          ) : (
            <ul className="divide-y">
              {items.map((n) => (
                <li
                  key={n.id}
                  className={cn(
                    "flex items-start justify-between gap-4 py-4",
                    !n.read_at && "bg-muted/30"
                  )}
                >
                  <div className="min-w-0 flex-1">
                    <div className="flex items-center gap-2">
                      <span className="font-medium">{n.title}</span>
                      {n.priority && n.priority !== "normal" && (
                        <Badge variant={n.priority === "urgent" || n.priority === "high" ? "destructive" : "secondary"}>
                          {n.priority}
                        </Badge>
                      )}
                      {!n.read_at && (
                        <Badge variant="outline" className="text-xs">New</Badge>
                      )}
                    </div>
                    {n.message && (
                      <p className="mt-1 text-sm text-muted-foreground">{n.message}</p>
                    )}
                    <p className="mt-1 text-xs text-muted-foreground">
                      {new Date(n.created_at).toLocaleString()}
                      {n.module && ` · ${n.module}`}
                    </p>
                  </div>
                  <div className="flex shrink-0 gap-2">
                    {n.related_record_id && n.module && (
                      <Button variant="outline" size="sm" asChild>
                        <Link href={`/${n.module}/${n.related_record_id}`}>View</Link>
                      </Button>
                    )}
                    {!n.read_at && (
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => handleMarkAsRead(n.id)}
                      >
                        Mark read
                      </Button>
                    )}
                  </div>
                </li>
              ))}
            </ul>
          )}
        </CardContent>
      </Card>
    </DashboardLayout>
  );
}
